import Foundation
import Testing

@testable import ModernPARCore

/// The native PAR1 engine end-to-end over the golden corpus generated by the original Intel
/// `par` binary: verify, repair (byte-exact restoration), renames, non-contributing files,
/// the padding quirk, and the retry-skip contract. (ROADMAP Phase 8)
@MainActor
struct Par1EngineTests {

    static let fixtures = Bundle.module.url(forResource: "Fixtures", withExtension: nil)!
        .appendingPathComponent("par1")

    /// Copies a fixture set's directory into a scratch folder (tests mutate freely).
    private func stage(_ subdir: String) throws -> URL {
        let scratch = FileManager.default.temporaryDirectory
            .appendingPathComponent("par1-engine-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.copyItem(
            at: Self.fixtures.appendingPathComponent(subdir), to: scratch)
        return scratch
    }

    private func run(
        anchor: String, in folder: URL, autoRepair: Bool = true,
        assumeVerified: [String]? = nil
    ) async throws -> [EngineEvent] {
        var route = SessionRoute(mode: .verifyRepair, autoRepair: autoRepair)
        route.folderBookmark = try? ScopedAccess.bookmark(for: folder)
        route.anchorBookmark = try ScopedAccess.bookmark(
            for: folder.appendingPathComponent(anchor))
        route.assumeVerifiedNames = assumeVerified
        var events: [EngineEvent] = []
        for await event in Par1Engine().run(route) { events.append(event) }
        return events
    }

    private func finalStatus(_ events: [EngineEvent]) -> DocStatus? {
        var status: DocStatus?
        for event in events {
            if case .docStatusChanged(let s) = event { status = s }
        }
        return status
    }

    private func succeeded(_ events: [EngineEvent]) -> Bool {
        for event in events.reversed() {
            if case .finished(let result) = event, case .success = result { return true }
        }
        return false
    }

    private func statuses(_ events: [EngineEvent]) -> [FileStatus] {
        var byID: [UUID: FileStatus] = [:]
        for event in events {
            if case .fileStatusChanged(let id, let status) = event { byID[id] = status }
        }
        return Array(byID.values)
    }

    private func corrupt(_ url: URL, at offset: Int = 5) throws {
        var data = try Data(contentsOf: url)
        data[offset] ^= 0xFF
        try data.write(to: url)
    }

    // MARK: - Verify

    @Test func healthyFiveFileSetVerifiesAllOK() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .allFilesOK)
        #expect(succeeded(events))
        #expect(statuses(events).allSatisfy { $0 == .ok })
    }

    @Test func unicodeRosterVerifiesAllOK() async throws {
        let folder = try stage("unicode")
        defer { try? FileManager.default.removeItem(at: folder) }
        let events = try await run(anchor: "unicode.par", in: folder)
        #expect(finalStatus(events) == .allFilesOK)
    }

    @Test func anchoringOnAParityVolumeWorks() async throws {
        // Volumes carry the identical roster — a set whose .par is gone still verifies.
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        try FileManager.default.removeItem(at: folder.appendingPathComponent("fivefiles.par"))
        let events = try await run(anchor: "fivefiles.p02", in: folder)
        #expect(finalStatus(events) == .allFilesOK)
    }

    // MARK: - Repair

    @Test func corruptFileIsRestoredByteExact() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("three.dat")
        let original = try Data(contentsOf: target)
        try corrupt(target)

        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(try Data(contentsOf: target) == original)
        // The damaged original moved aside, never destroyed.
        #expect(FileManager.default.fileExists(atPath: target.path + ".1"))
        #expect(statuses(events).contains(.recovered))
    }

    @Test func threeMissingFilesRecoverThroughAllThreeVolumes() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        var originals: [String: Data] = [:]
        for name in ["one.dat", "three.dat", "five.dat"] {
            let url = folder.appendingPathComponent(name)
            originals[name] = try Data(contentsOf: url)
            try FileManager.default.removeItem(at: url)
        }
        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        for (name, data) in originals {
            #expect(try Data(contentsOf: folder.appendingPathComponent(name)) == data)
        }
    }

    @Test func fourMissingFilesNeedOneMore() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        for name in ["one.dat", "two.dat", "three.dat", "four.dat"] {
            try FileManager.default.removeItem(at: folder.appendingPathComponent(name))
        }
        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .needMoreFiles(count: 1))
        #expect(succeeded(events))
    }

    @Test func verifyOnlyStopsAtRepairNeeded() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("two.dat")
        try corrupt(target)
        let damaged = try Data(contentsOf: target)

        let events = try await run(anchor: "fivefiles.par", in: folder, autoRepair: false)
        #expect(finalStatus(events) == .repairNeeded)
        // Verify-only must not touch the disk.
        #expect(try Data(contentsOf: target) == damaged)
    }

    @Test func singleVolumeSetRecoversOneMissingFile() async throws {
        let folder = try stage("single-volume")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("second.dat")
        let original = try Data(contentsOf: target)
        try FileManager.default.removeItem(at: target)

        let events = try await run(anchor: "single.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(try Data(contentsOf: target) == original)
    }

    @Test func emptyFileRecovers() async throws {
        let folder = try stage("empty-file")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("empty.dat")
        try FileManager.default.removeItem(at: target)

        let events = try await run(anchor: "emptyset.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(FileManager.default.fileExists(atPath: target.path))
        #expect(try Data(contentsOf: target).isEmpty)
    }

    @Test func biggerSetRecoversTheLargeFile() async throws {
        let folder = try stage("bigger")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("big.dat")
        let original = try Data(contentsOf: target)
        try FileManager.default.removeItem(at: target)

        let events = try await run(anchor: "bigger.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(try Data(contentsOf: target) == original)
    }

    @Test func damagedVolumeIsIgnoredAndOthersRecover() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        // Corrupt p01's parity area: its control hash fails, leaving p02/p03.
        let volume = folder.appendingPathComponent("fivefiles.p01")
        var data = try Data(contentsOf: volume)
        data[data.count - 10] ^= 0xFF
        try data.write(to: volume)
        let target = folder.appendingPathComponent("four.dat")
        let original = try Data(contentsOf: target)
        try FileManager.default.removeItem(at: target)

        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(try Data(contentsOf: target) == original)
        let logs = events.compactMap {
            if case .logLine(let l) = $0 { return l } else { return nil }
        }
        #expect(logs.contains { $0.contains("damaged parity volume") })
    }

    // MARK: - Renames (fix faulty filenames)

    @Test func renamedFileIsFixedWithoutRecovery() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let original = folder.appendingPathComponent("two.dat")
        let content = try Data(contentsOf: original)
        try FileManager.default.moveItem(
            at: original, to: folder.appendingPathComponent("wrongname.bin"))

        let events = try await run(anchor: "fivefiles.par", in: folder)
        // Rename-only repair: nothing was rebuilt (DocStatus6).
        #expect(finalStatus(events) == .allFilesOKWithRenames)
        #expect(try Data(contentsOf: original) == content)
        #expect(
            !FileManager.default.fileExists(
                atPath: folder.appendingPathComponent("wrongname.bin").path))
        #expect(statuses(events).contains(.renamed(from: "wrongname.bin")))
    }

    @Test func renamePlusRecoveryReportsRestoredWithRenames() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        try FileManager.default.moveItem(
            at: folder.appendingPathComponent("two.dat"),
            to: folder.appendingPathComponent("misplaced.xyz"))
        let lost = folder.appendingPathComponent("five.dat")
        let lostContent = try Data(contentsOf: lost)
        try FileManager.default.removeItem(at: lost)

        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .restoredWithRenames)
        #expect(try Data(contentsOf: lost) == lostContent)
        #expect(
            FileManager.default.fileExists(atPath: folder.appendingPathComponent("two.dat").path))
    }

    // MARK: - Non-contributing files (doc-01: verifiable, never repairable)

    @Test func missingNonContributingFileIsOnlyNonRecoverable() async throws {
        let folder = try stage("noncontrib")
        defer { try? FileManager.default.removeItem(at: folder) }
        try FileManager.default.removeItem(at: folder.appendingPathComponent("extra.dat"))

        let events = try await run(anchor: "noncontrib.par", in: folder)
        #expect(finalStatus(events) == .onlyNonRecoverableMissing)
        #expect(statuses(events).contains(.unrecoverableMissing))
    }

    @Test func paddingQuirkSetRecoversContributingFile() async throws {
        // The Intel binary sizes volume data areas to the largest ROSTER file (including
        // non-contributing ones), zero-filled past the contributing parity — recovery must
        // read only the contributing extent. (Fixture corpus finding)
        let folder = try stage("noncontrib-large")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("s1.dat")
        let original = try Data(contentsOf: target)
        try FileManager.default.removeItem(at: target)

        let events = try await run(anchor: "pad.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(try Data(contentsOf: target) == original)
    }

    // MARK: - Retry skip (sticky-OK)

    @Test func assumeVerifiedSkipsRehashingUnchangedFiles() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        // Same-size content change is NOT detected when the file is on the skip list —
        // that is the documented trade of the original's "remembers OK files" behavior.
        let target = folder.appendingPathComponent("one.dat")
        var data = try Data(contentsOf: target)
        data[0] ^= 0xFF
        try data.write(to: target)

        let events = try await run(
            anchor: "fivefiles.par", in: folder,
            assumeVerified: ["one.dat", "two.dat", "three.dat", "four.dat", "five.dat"])
        #expect(finalStatus(events) == .allFilesOK)
    }

    @Test func assumeVerifiedRevalidatesWhenSizeChanges() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("one.dat")
        var data = try Data(contentsOf: target)
        data.append(0x42)  // size change invalidates the skip
        try data.write(to: target)

        let events = try await run(
            anchor: "fivefiles.par", in: folder, autoRepair: false,
            assumeVerified: ["one.dat"])
        #expect(finalStatus(events) == .repairNeeded)
    }

    // MARK: - Review regressions (Phase 8)

    @Test func hugeVolumeNumberVolumeIsIgnoredNotACrash() async throws {
        // A crafted volume with volumeNumber 2^63 passes the set-hash and control-hash
        // guards; converting it unchecked trapped the whole app. (Phase 8 review)
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        var data = try Data(contentsOf: folder.appendingPathComponent("fivefiles.p03"))
        let huge: UInt64 = 0x8000_0000_0000_0000
        for i in 0..<8 {
            data[0x30 + i] = UInt8(truncatingIfNeeded: huge >> (8 * UInt64(i)))
        }
        let control = MD5Digest.hash(Data(data[0x20...]))
        for (i, byte) in control.bytes.enumerated() { data[0x10 + i] = byte }
        try data.write(to: folder.appendingPathComponent("fivefiles.p07"))

        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .allFilesOK)
        let logs = events.compactMap {
            if case .logLine(let l) = $0 { return l } else { return nil }
        }
        #expect(logs.contains { $0.contains("invalid volume number") })
    }

    @Test func directorySquattingOnAMissingNameIsBackedUpNotDeleted() async throws {
        // A DIRECTORY occupying a roster file's name classified the entry as missing, and
        // the recovery writer recursively deleted the directory — silent data loss reported
        // as success. The occupant must move aside as a .1 backup instead. (Phase 8 review)
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let target = folder.appendingPathComponent("three.dat")
        let original = try Data(contentsOf: target)
        try FileManager.default.removeItem(at: target)
        try FileManager.default.createDirectory(at: target, withIntermediateDirectories: false)
        let precious = target.appendingPathComponent("precious.txt")
        try Data("user data".utf8).write(to: precious)

        let events = try await run(anchor: "fivefiles.par", in: folder)
        #expect(finalStatus(events) == .restoredSuccessfully)
        #expect(try Data(contentsOf: target) == original, "the roster file must be restored")
        let backup = folder.appendingPathComponent("three.dat.1")
        var isDirectory: ObjCBool = false
        _ = FileManager.default.fileExists(atPath: backup.path, isDirectory: &isDirectory)
        #expect(isDirectory.boolValue, "the squatting directory must survive as a backup")
        #expect(
            (try? Data(contentsOf: backup.appendingPathComponent("precious.txt")))
                == Data("user data".utf8),
            "the directory's contents must be intact")
    }

    // MARK: - Session integration

    @Test func openingAPar1SetAutoVerifiesThroughTheNativeEngine() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        let session = OperationSession()
        session.open(
            folder.appendingPathComponent("fivefiles.par"),
            thenVerifyUsing: Par1Engine(), autoRepair: true)
        for _ in 0..<400 where session.isBusy || session.docStatus == .checking {
            try await Task.sleep(for: .milliseconds(25))
        }
        #expect(session.docStatus == .allFilesOK)
        #expect(session.rows.count == 5)
        #expect(session.rows.allSatisfy { $0.status == .ok })
    }

    @Test func engineRouterDispatchesByAnchorForm() async throws {
        let folder = try stage("five-files")
        defer { try? FileManager.default.removeItem(at: folder) }
        struct FailingEngine: PAR2Engine {
            func run(_ route: SessionRoute) -> AsyncStream<EngineEvent> {
                AsyncStream { c in
                    c.yield(.finished(.failure(.notImplemented)))
                    c.finish()
                }
            }
        }
        // A .par anchor must reach the PAR1 side of the router.
        let router = EngineRouter(par2: FailingEngine(), par1: Par1Engine())
        var route = SessionRoute(mode: .verifyRepair, autoRepair: true)
        route.folderBookmark = try? ScopedAccess.bookmark(for: folder)
        route.anchorBookmark = try ScopedAccess.bookmark(
            for: folder.appendingPathComponent("fivefiles.par"))
        var events: [EngineEvent] = []
        for await event in router.run(route) { events.append(event) }
        #expect(finalStatus(events) == .allFilesOK)
    }
}
